// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBV7HGyAR87WnslHd4y3wVMtZYzfqoXW0',
    appId: '1:652887940699:web:b7f380997c2cf6cd0ba97e',
    messagingSenderId: '652887940699',
    projectId: 'maddemo-621ab',
    authDomain: 'maddemo-621ab.firebaseapp.com',
    storageBucket: 'maddemo-621ab.firebasestorage.app',
    measurementId: 'G-J7Z02X93CV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5hTn4yRStUIBBqfGQp-RHtw5g8YUGcfU',
    appId: '1:652887940699:android:ecdaab744f23a7470ba97e',
    messagingSenderId: '652887940699',
    projectId: 'maddemo-621ab',
    storageBucket: 'maddemo-621ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATwj1SeTs1rhoTJgHUNAvyCr84l-k2_7w',
    appId: '1:652887940699:ios:6bfd31205cc9e60e0ba97e',
    messagingSenderId: '652887940699',
    projectId: 'maddemo-621ab',
    storageBucket: 'maddemo-621ab.firebasestorage.app',
    iosBundleId: 'com.example.madDemoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATwj1SeTs1rhoTJgHUNAvyCr84l-k2_7w',
    appId: '1:652887940699:ios:6bfd31205cc9e60e0ba97e',
    messagingSenderId: '652887940699',
    projectId: 'maddemo-621ab',
    storageBucket: 'maddemo-621ab.firebasestorage.app',
    iosBundleId: 'com.example.madDemoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBV7HGyAR87WnslHd4y3wVMtZYzfqoXW0',
    appId: '1:652887940699:web:6f34c3185f69833c0ba97e',
    messagingSenderId: '652887940699',
    projectId: 'maddemo-621ab',
    authDomain: 'maddemo-621ab.firebaseapp.com',
    storageBucket: 'maddemo-621ab.firebasestorage.app',
    measurementId: 'G-D8JZW15771',
  );
}
